### ISSUE TITLE
Don't make user call super.connect or super.disconnect

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-element#20]
Right now if the user implements `connect` or `disconnect`, they have to call the `super` method so that the lifecycle mixin can track that those lifecycle hooks have run. We should make it so they don't have to do this.

Maybe the same should apply for `initialize` and `render`? Since those will mostly be used by other mixins, maybe this isn't encessary?

**Comment by matthewp** [comment]
I think the hooks called by us on behalf of the user should not need super() called. These are for the end developer. So if we need to have our own `connect()` then we should make it automatically be called.

**Comment by phillipskevin** [comment]
I think we have "framework hooks":

- connectedCallback
- disconnectedCallback
- initialize
- render

These are implemented by framework mixins and can be called by the user (primarily for testing). If the user wants to implement these, they will need to call `super`.

And we have "user hooks":
- connect
- disconnect

This is where the user should put their code without having to call `super`.

**Comment by justinbmeyer** [comment]
> This is where the user should put their code without having to call super.

And by avoiding super ... they are avoiding the awareness that our "framework hooks" call `user hooks` based on state (if the user hook has been called or not yet).
