### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-element#32]
## https://canjs.com/doc/can-stache-define-element.html

- [x] https://docs.google.com/document/d/1mLCBUBp2yntjshRBNbMOri_Ya1fXu0VZizYe_VwlP08/edit#

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/static.view.html

First signature

- [x] The purpose of a view isn't described.
- [x] `<p>{{name}}</p>` should be `<p>{{ this.name }}</p>`
- [x] `<input type="checkbox" checked:bind="this.complete">`
- [x] The initial example shows using `todo.render({ name: "go grocery shopping" });` instead of a view in the page.


Second signature:

- [x] `static get define() { return { ... } }` this should be `static get view...`
- [x] I think this can show just what's needed, not a complete example.

Other:

- needs details about purpose, also clearly defining when the view gets rendered, what it gets rendered with, where the view is rendered, etc.

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/static.define.html

First signature:

- [x] We need to describe why someone would want to define these properties.

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.connectedCallback.html

Description:

- [x] _Implementation of the connectedCallback lifecycle method of custom elements._ ... This should describe a bit more of the purpose of reading this page for a user.

Signature:

- [x] There's no description. There's no introduction to the example.  


I think the big thing we want people to know is that:

1.  They should __not__ implement connectedCallback themselves.  They should implement `connected()` instead.
2. `connectedCallback()` calls the other initialize methods, which results in calling `connected()`.

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.initialize.html

- [x] the first signature has no description.

- [x] We should make this return the instance.  Then we can show `new MyElement().initialize(props)`

- [x] _After initialize has been called, subsequent calls will not have any effect._ Is this true?

- [x] `<p>{{age}}</p>` => `<p>{{ this.age }}</p>`

- [x] A bit of the purpose should be included in the signature or description.

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.render.html

- [x] Simlar issues as `.initialze()`

### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.connect.html

- [x] Similar issues as `.initialize()`

### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.disconnectedCallback.html

- [x] Similar issues as `.connectedCallback()`
- [x] We should tell people about `this.stopListening()` being called ...

### https://canjs.com/doc/can-stache-define-element/lifecycle-methods.disconnect.html

- [x] Similar issues as `.initialize()`

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/lifecycle-hooks.connected.html

- [x] We should make sure people know they implement this method instead of connectedCallback
- [x] Signature doesn't have a description. What purpose does this solve?

**Comment by justinbmeyer** [comment]
### https://canjs.com/doc/can-stache-define-element/lifecycle-hooks.disconnected.html

- [x] signature doesn't have a description. Some of the page description should be moved to the signature description.

**Comment by phillipskevin** [comment]
> After initialize has been called, subsequent calls will not have any effect. Is this true?

Yes, this is true.
