### ISSUE TITLE
Cannot listen to dom events from child elements

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache-element#34]
This codepen shows the problem. When a child element dispatches a bubbling event you can't listen to it. `addEventListener` and `listenTo` both do not work, as far as I can tell.

Also `on:some-event="this.doSomething()"` doesn't work, nor does `on:el:some-event="this.doSomething()"` but those are stache-bindings issues I suppose.

cc @justinbmeyer @phillipskevin 

https://codepen.io/matthewp/pen/XLNXvE

**Comment by justinbmeyer** [comment]
Is this because can-event-queue is overwriting addEventListener?

**Comment by matthewp** [comment]
That's the problem with `addEventListener`. I'm not sure about `listenTo` or `on:some-event` or `on:el:some-event`.
