### ISSUE TITLE
Allow users to set a property using an attribute

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-element#4]
@phillipskevin commented on [Mon Apr 15 2019](https://github.com/canjs/can-element/issues/53)

We need some way of allowing users to set the property of an element using an attribute.

**Option 1**

One option is to always set properties if they exist,

```js
class TodosApp extends HTMLElement {
  name = null;
}
```

```html
<todos-app name="do dishes"></todos-app>
```

**Option 2**

Another option is to create a mixin that will allow the user to opt-in to setting camelCase properties using kebab-case attributes:

```js
@connectAttributes() // makes it so setting an attribute sets
                     // the camelized property
class BitToc extends HTMLElement {
}
```

**Option 3**

Another option is to make it possible to specify this on a per-property basis:

(this example is taken from the Stencil docs, since it is what they do)

```js
export class TodoList {
   @Prop() color: string;
   @Prop() favoriteNumber: number;
   @Prop() isSelected: boolean;
   @Prop() myHttpService: MyHttpService;
}
```

```html
<todo-list color="blue" favorite-number="24" is-selected="true"></todo-list>
```

**Comment by phillipskevin** [comment]
I'm not sure we need this, but leaving it open for now.

**Comment by Mattchewone** [comment]
## Proposal

```js
class App extends StacheElement {
  static props = {
    firstName: type.maybeConvert(String)
  };

  static view = "<h1>{{firstName}}</h1>";

  static attrs = ['firstName']
}
customElements.define("a-pp", App);
```
```html
<a-pp firstName="Matt" />
```

This would internally setup the `observedAttributes` and `attributeChangedCallback` to something similar to this:

```js
class App extends StacheElement {
  static props = {
    firstName: type.maybeConvert(ObservableObject)
  };

  static view = "<h1>{{firstName}}</h1>";

  static get observedAttributes() { return [ 'firstName' ]; }

  attributeChangedCallback(name, oldValue, newValue) {
    this[name] = newValue;
  }
}
customElements.define("a-pp", App);
```

However this `<a-pp person="{ name: 'Matt' }">` would not work, even with `type.convert(ObservableObject)`. The output is an object which has key/value for each character in the string. So we would need a way to handle being given objects as strings and parsing them, *if* we want to be able to handle objects as strings.

**Comment by phillipskevin** [comment]
@Mattchewone would this also set up a listener for `firstName` and set the attribute if the `firstName` property changes (only in situations where the attribute has been set).

@matthewp suggested looking at how newer elements (`<video>`, `<picture>`, `<detail>`, `<summary>`, ...) handle this.

**Comment by Mattchewone** [comment]
@phillipskevin So I would think that we would create listeners for each of the `attrs`, as those would be the `attributes` that we would want to update right? Or are you thinking we would have listeners for every defined prop and then upon change check if that property has a corresponding attribute?

**Comment by Mattchewone** [comment]
We would also have to account for updating the attribute presumably would trigger a `attributeChangedCallback` so would need a check to prevent it from updating the property. 

What is the benefit of updating the `attribute` on property change?

**Comment by justinbmeyer** [comment]
```
class App extends StacheElement {
  static props = {
    firstName: type.maybeConvert(String)
  };

  static view = "<h1>{{firstName}}</h1>";

  static attrs = ['firstName']
}
customElements.define("a-pp", App);
```

Do we need `attrs` if we have `props`?

**Comment by matthewp** [comment]
I would have an `attributes: true` or something like that.

Note that if you want to use the PropDefinition way you'll need to call `finalizeClass` inside of `observedAttributes` since that is called when `customElements.define` is called.

**Comment by phillipskevin** [comment]
> What is the benefit of updating the attribute on property change?

Some elements do this (for example the [meter](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element) element has these requirements). I think this is mainly for accessibility, but could also be useful for styling.

> Do we need attrs if we have props?

I think it's somewhat likely that you would only care about setting properties from a few attributes and less likely you would want setting any attribute to also set the property.

> I would have an attributes: true or something like that.

@matthewp, you mean each PropertyDefinition would have that option? Like:

```js
  static props = {
    firstName: {
      type: type.maybeConvert(String),
      attribute: true
    }
  };
```

**Comment by justinbmeyer** [comment]
```
<my-component {{#if foo}}enabled{{/if}}/> ""-> false

<my-component aria-x="undefined"/>

element.prop = {}
element.prop = "{}"
eleement.setAttribute("prop","{}")

props = {
    ariaE: String
    ariaX: maybe(String)
    ariaY: convert(String)
    ariaZ: maybeConvert(String)

    ariaE: Number
    ariaX: maybe(Number)
    ariaY: convert(Number)
    ariaZ: {
        type: maybeConvert(Todo),
        attribute: true
    }


    ariaE: Todo
}

USE CASES 

    1. Element updating its attributes by setting properties.
        ```
        constructor(){
            // ariaE
            this.setAttribute("aria-e","thing");
            this.setAttribute("aria-e","");
            this.removeAttribute("aria-e") //-> error?

            this.removeAttribute("aria-x") //-> set to null 


            this.ariaE = 5 //-> setAttribute("aria-e",5) ?

            this.setAttribute("aria-z", Todo);
        }
        
        ```


// what happens with element-wide attributes?
<my-component id="hello" class="abc" data-foo="abc" aria-x="value"/>

DIMENSIONS:


- binding directions
- syntax 


1. prop <-> bindings for everything in props 
        <my-component value="x">

        MyComponent extends StacheElement {
            static props  = {
                value: String,
                todoPromise: {
                    enumerable: true,
                    get: function(){
                        
                    }
                }
            }
            connected(){
                this.value //-> "x"
            }
        }

        - if two way-bindings ... todoPromise
        
        
2.a Specify prop <-> bindings in prop def 

        MyComponent extends StacheElement {
            static props = {value: {attribute: true}}
            
            connected(){
                this.value //-> "x"
            }
        }
2.a Specify prop <-> bindings in some array 

        MyComponent extends StacheElement {
            static props = {value: {}};
            static attrs = ["value"]
            
            connected(){
                this.value //-> "x"
            }
        }
```

**Comment by phillipskevin** [comment]
Based on the conversation above we agreed on:

1. The user is going to have to opt-in to which attributes they want to bind to properties, because it will only be possible to convert a small range of `type`s to attributes
2. For each attribute the user has opted in to, we will set up "two-way binding" so that if the attribute is set, the property will be set and if the property is set the attribute will be set

Open questions:

1. How should the user opt-in?

1a. `attribute: true` on the property definition

```js
  static props = {
    name: { type: String, attribute: true }
  };
```


Benefits:
- configuration will be in the same place as everything else related to the property
Downsides
- currently `can-define-mixin` handles `props`, but `attribute: true` only applies to `StacheElement`. We would either have to handle `props` in two separate places, or make this code check that `this instanceof HTMLElement` is true before handling the `attribute: true` properties. We would also have to figure out how to document this.

1a. `static attrs` 

```js
  static props = {
    name: String
  };
  static attrs = [ "name" ];
```

Benefits: specific to StacheElement
Downsides: separate from rest of peroperty definition

2. How do we handle properties that cannot be converted to Strings?

These `type`s will work:

```
String
maybe(String)
convert(String)
maybeConvert(String)

convert(Number)
maybeConvert(Number)
```

Other types will throw. Is that ok?

3. Is two-way binding correct?

Some custom element frameworks ([Stencil](https://stenciljs.com/docs/properties#prop-decorator), [SkateJS](https://skatejs.netlify.com/docs/element)) don't reflect property changes to attributes by default. They do this for different reasons, the biggest of which seem to be that this will cause virtual dom libraries to do unnecessary diffs and that setting attributes is somewhat slow.

Since the property -> attribute direction is much less useful than the other direction, perhaps we should punt on this for now and just handle updating properties when attributes change.

**Comment by justinbmeyer** [comment]
> We would either have to handle props in two separate places

yeah, I think we should handle props in two separate places then. Is there difficulty with this?

>  perhaps we should punt on this for now and just handle updating properties when attributes change.

I agree.  I wonder if we could make the following work:

```js
import {StacheElement, fromAttribute} from "http://canjs.com/core.mjs";

class StrictInput extends StacheElement {
  static view = `<input value:bind="this.value"/>`;
  static seal = true;
  static props = {
    value: {type: String, required: true, bind: fromAttribute}
  }
}
customElements.define("strict-input", StrictInput);
```

The function passed to `bind` would return a `new Bind()`.  It would be called with:

- the `this`
- the key
-  the property definition. For example:

```js
function fromAttribute(element, propertyName) {
  return new Bind({
    parent: new AttributeObservable(element, camelize(propertyName)),
    child: value.to( element, propertyName)
  });
}
```

The cool thing about this is that it would be easy to create other properties that connect to other values:

```js
fromWindowWidth = function(obseravble, prop){
  var windowWidth = new Resolver(( {listenTo, resolve} ) =>{
    resolve( window.innerWidth )
    listenTo(window, "resize", ()=> resolve(window.innerWidth) )
  })
  return new Bind({
    child: value.to(this, prop),
    parent: windowWidth
  });
}

class MySlider extends StacheElement {
  static view = `...`;
  static props = {
    width: {type: String, required: true, bind: fromWindowWidth}
  }
}
```

To make this work, we'd create a mixin (only working on elements for now), that would loop through props and look for `bind` functions.  Upon `connectedCallback()`, all the bindings would be `.start()`ed.  They would all be stopped on disconnect.

## Problems 

I just realized that my suggested used `AttributeObservable` (via async MutationObserver) instead of the sync `attributeChangedCallback`.  

It might still be possible to make it work with `attributeChangedCallback`, but a different sort of `AttributeObservable` would need to be created.

Also, if we initialize these bindings in `connectedCallback()` the element's properties will not be initialized with its attribute values.  This might be unexpected in terms of testing and such. Similar to `.bindings()`, we might want to run these during `initialize()`.

**Comment by Mattchewone** [comment]
I have been reading through the docs of the other custom element libraries such as `stencil` / `litElement` / `SkateJS`

None of the above libraries by default have two way attribute <-> property binding enabled, they all provide ways to do two way binding but it's opt-in.

Both `litElement` and `stencil` use the definition `{ reflect: true }` to enable reflecting property changes into attributes. 
`litElement` have a way to provide custom conversion which I think is neat.

```js
prop1: {
  reflect: true,
  converter: { 
    fromAttribute: (value, type) => { 
      // `value` is a string
      // Convert it to a value of type `type` and return it
    },
    toAttribute: (value, type) => { 
      // `value` is of type `type` 
      // Convert it to a string and return it
    }
  }
}
```

Under the hood this is something we would be doing by default but allowing the exposure of it could provide more fine grained control.

`stencil` will only create attributes for properties if the properties are primitives, the default behaviour can be overriden but I am not sure on the outcome of this yet.

**Comment by justinbmeyer** [comment]
```
function fromAttribute(class, propertyName) {
  addToYourAttribute()
  
  return function(instance){
      return new Bind({
        parent: new ElementAttributeObservable(element, camelize(propertyName)),
        child: value.to( instance, propertyName)
      });
  }
}
```

```js
function finalizeClass(){
  return constuctor(){
    
     return {
        initialized() {
            bind.start();
        },
        connected() {},
        rendered(){},
        disconnected(){
          bind.stop();
        }
     }
  }
}
```

**Comment by Mattchewone** [comment]
- [x] 1.  Split https://github.com/canjs/can-stache-element/blob/major/src/mixin-bindings.js into 2 different mixins.  One for initialization.  Another for actual `.bindings()` method.

- [x] 2.  Create another mixin, for searching for `bind` prop behaviors + calling them at the right time, make it so bindings find themselves in the `initialization` mixin in step 1.

- [x] 3.  Create fromAttribute with AttributeObservable.

- [ ] 4.  Maybe make fancy ElementAttributeObservable.

**Comment by Mattchewone** [comment]
Where should the `fromAttribute` method exported from? Should it be an export of `StacheElement`?

**Comment by phillipskevin** [comment]
I think `fromAttribute` should be in another project. Something like `can-observable-bindings`.

**Comment by Mattchewone** [comment]
Will need to update `fromAttribute` to handle being passed a class so that it can add `attributeChangedCallback` to the proto after being called from `StacheElements` mixins.

```js
function fromAttribute(propertyName) {
    return function(ctr) {
        if(!ctr.hasSetupStuff) {
            ctr.attributeArrayStuff = [];
            ctr.attributeBindings = [];
            
            Object.defineProperty(ctr, "observedAttributes", {
                get() {
                    return ctr.attributeArrayStuff;
                }
            })
            
            ctr.prototype.attributeChangedCallback = function(prop, newVal, oldVal) {
                // do stuff
                for(binding of ctr.attributeBindings) {
                    binding.update(prop, newVal, oldVal)
                }
            }
        }
        ctr.attributeArrayStuff.push(prop);
        
        return function(instance) {
            let binding = new Bind({
                // whatever
            });
            ctr.attributeBindings.push(binding);
            return binding;
        };
    }
}
```

**Comment by phillipskevin** [comment]
https://github.com/canjs/can-stache-element/issues/62 is a follow-on to this.
