### ISSUE TITLE
When inserted into stache, throws if render() is not called

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache-element#44]
The latest nodeList fixes properly teardown everything when an element is removed (yay). However in stache the element will be inserted *before* connectedCallback() is called.

When this happens viewInsertSymbol pushes `undefined` into the nodeLists: https://github.com/canjs/can-stache-define-element/blob/37d0a61f29a5d9a4c3fe1e849b4715e1dbb96afc/src/mixin-stache-view.js#L73-L77

This will wind up throwing when the element is later removed. I think viewInsertSymbol should call `render()`. This is what can-component does: https://github.com/canjs/can-component/blob/47a1024b57e82d559c625b61a18b1b84cddcaa72/can-component.js#L704

cc @justinbmeyer @phillipskevin

**Comment by phillipskevin** [comment]
I think it makes sense for the viewInsertSymbol to call `render`. We'll just need to make sure that `connect` eventually gets called when the element is actually inserted.

**Comment by justinbmeyer** [comment]
Yeah, in 6.0, we will probably want to listen to “inserted” and do something similar.
