### ISSUE TITLE
StacheElement cannot be used as route.data

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-element#56]
This codepen shows the bug: https://codepen.io/kphillips86/pen/XLOBYb?editors=0011

If you change the URL, the `count` will be updated correctly, but if you click the `+1` button, the route does not change.

This is because `canReflect.serialize` does not serialize StacheElements correctly.

**Comment by phillipskevin** [comment]
The first step to making this work is to change `isBuiltIn`:

https://github.com/canjs/can-reflect/blob/c59a2897251f7c34cb1b662795ed00f41a0a5d45/reflections/type/type.js#L191-L192

...so that it returns false for custom elements. This is because built-ins are always treated as already serialized:

https://github.com/canjs/can-reflect/blob/804c5ee6cbb86c00b40dbca5be44e1335ca6c7cd/reflections/shape/shape.js#L169-L171

**Comment by justinbmeyer** [comment]
Could we just check `isObservableLike`?

**Comment by phillipskevin** [comment]
Yeah, that would work I think. I'll try it when I get back to this.
