### ISSUE TITLE
Make fromAttribute synchronous

### ISSUE THREAD

**Issue by Mattchewone** [canjs/can-stache-element#62]
Will need to update `fromAttribute` to handle being passed a class so that it can add `attributeChangedCallback` to the proto after being called from `StacheElements` mixins.

The `StacheElement` mixin will need to change how it calls the `bind` function so that it can pass it the class constructor.

Example from @matthewp psuedo-code / implementation.
```js
function fromAttribute(propertyName) {
    return function(ctr) {
        if(!ctr.hasSetupStuff) {
            ctr.attributeArrayStuff = [];
            ctr.attributeBindings = [];
            
            Object.defineProperty(ctr, "observedAttributes", {
                get() {
                    return ctr.attributeArrayStuff;
                }
            })
            
            ctr.prototype.attributeChangedCallback = function(prop, newVal, oldVal) {
                // do stuff
                for(binding of ctr.attributeBindings) {
                    binding.update(prop, newVal, oldVal)
                }
            }
        }
        ctr.attributeArrayStuff.push(prop);
        
        return function(instance) {
            let binding = new Bind({
                // whatever
            });
            ctr.attributeBindings.push(binding);
            return binding;
        };
    }
}
```

**Comment by justinbmeyer** [comment]
Why 3 functions?  I think in the version I suggested (in some issue), it was more like:

```js
function fromAttribute(Class, propertyName) {
  return function(instance){ ... }
}
```

---------


I see why it's happening.  I think we should make it work if simply provided to `bind`.

**Comment by justinbmeyer** [comment]
There also seems like a memory leak by adding bindings to a class.  I was thinking it would simply add to a `this._bindings` array.

**Comment by Mattchewone** [comment]
@justinbmeyer What do you mean by:
>  I think we should make it work if simply provided to bind.

I am not sure I understand. This issue is for updating to provide the synchronous version using `observedAttributes` and `attributeChangedCallback`.

Could you elaborate more on the memory leak? Are you seeing issue with the binding being torn down?

**Comment by justinbmeyer** [comment]
Let’s talk about it. We shouldn’t add bindings to the class.

**Comment by phillipskevin** [comment]
@justinbmeyer as we talked about, bindings aren't being added to the class.

@Mattchewone's code for this is in progress here: https://github.com/canjs/can-observable-bindings/pull/3/files.

We can have a discussion once he has a chance to get it working, but the general idea is that bindings are being added on the instances `metaSymbol`

**Comment by phillipskevin** [comment]
this can be closed, right, @Mattchewone ?

**Comment by Mattchewone** [comment]
Yup all done now!
