### ISSUE TITLE
Passing templates that retain their scope (`<can-template>` Component feature)

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-element#77]
We need to be able to pass templates to a `StacheElement` and have those templates retain their scope.  This does not currently work with using inline partials (`{{<inlinePartial}}`).

This can be seen in this example: https://codepen.io/justinbmeyer/pen/XWrqWWe?editors=0010

In that example, I'd like `{{this.text}}` to be able to render with `this` as the scope of the `view` (`{text: "Right text"}`) instead of the scope that is passed to `{{{modalContent(text="WRONG TEXT")}}}`.  This is how `<can-template>` and `<content>` work with Component.

This is a very important feature. It might be hard to consider `StacheElement` production-ready without it.

**Comment by justinbmeyer** [comment]
The easy solution might be to make <can-template> pass these views as properties. 
For example:

```
{{# for( val in this.list ) }}
<my-custom-element>
  <can-template name="xyz">{{val}}</can-template>
</my-custom-element>
{{ / }}
```

This would set the template `{{val}}` function as the `xyz` property on the `<my-custom-element>` instance.

In `my-custom-element`, the view would render the function as follows:

```
static view = `{{xyz()}}`
```

Similar to how to [can-slot](https://canjs.com/doc/can-component/can-slot.html) can pass template variables down to the `<can-template>`, we can provide the same thing as follows:

```
static view = `{{xyz( a="b" )}}`
```

I like this for two reasons:

- If folks are already using `<can-template>` we are at least 1/2 way more compatible.
- We don't need to decide on a new syntax right now.  We just use the old one.
- This will be easier to implement.


### Implementation

I believe that the constructor will already be called with these templates in `tagData.templates` [here](https://github.com/canjs/can-stache-element/blob/b3d6ffbf68609633377a4f73ed0229c5bdd13e63/src/can-stache-element.js#L33). This is passed by `can-stache` already [here](https://github.com/canjs/can-stache/blob/078c82dd230b5688ef90166600c48e6fe82449ec/can-stache.js#L324).

All we need to do is loop through those templates and add them to the stacheElement instance.

**Comment by matthewp** [comment]
Can you explain the problem with this?

```handlebars
{{# for( val in this.list ) }}
  {{< xyz }}
    {{val}}
  {{/ xyz }}
  <my-custom-element xyz="xyz"></my-custom-element>
{{ / }}
```

**Comment by justinbmeyer** [comment]
I didn’t think inline partials are put in Let scope. Are they? (I also think this would end up re-creating the partial, which wouldn’t be great for performance, although this could be happening for can-template too)

**Comment by matthewp** [comment]
Yeah, none of these ideas work at the moment. I would expect performance to be equivalent since they are both producing subtemplates.

I like the partial idea better because:

* One less thing to learn.
* I expected to be able to use template-scoped variables inside of the partial anways, so it's an existing bug in my mind.
* `<can-template>` is a little confusing because it looks like an element but is actually a template macro.

**Comment by justinbmeyer** [comment]
I find the partial idea a bit more cumbersome / less ergonomic.  You have to create the template AND pass it. And, if you wanted to access `this`, you'd have to declare it too. Ideally, we'd support the following:

```
{{# for( val in this.list ) }}
  <my-custom-element>
  {{< xyz }}
    {{val}} {{this.prop}}
  {{/ xyz }}
  </my-custom-element>
{{ / }}
```

I'm pretty sure there is an issue around this.

Yeah, neither of these work now, but `<can-template>` is __much__ easier to implement and the documentation could mostly be copied right now. I'd favor this approach for now until the above signature can be made to work.

**Comment by phillipskevin** [comment]
What about something like this?

```html
{{< xyz }}
  {{ this }}
{{/ xyz }}

{{# for(val in this.list) }}
  <my-custom-element xyz="xyz.bind(val)"></my-custom-element>
{{/ for }}
```

This also doesn't work currently, but I think it wouldn't be too much work to add support for this to `ScopeKeyData` and Call Expressions.

I like it because it is more in line with the direction we've been taking stache to be more "JavaScript-y".

**Comment by phillipskevin** [comment]
I think maybe all three of these options should work. I don't know which one users would find most intuitive.

@justinbmeyer if you want to make `<can-template name="xyz">{{val}}</can-template>` work with `StacheElement` so you can continue working on `can-crud`, we can use this issue for that and open separate issues for the other two (if @matthewp's suggestion doesn't already have one).

**Comment by justinbmeyer** [comment]
Just to be clear, here's my take on the 3 options:

## `<can-template>`

```handlebars
<my-custom-element>
  <can-template name="xyz">{{val}}</can-template>
</my-custom-element>
```

Pros:

- easy to implement
- semi backwards compatible
- HTMLish API (similar to custom elements)

Cons:

- Not very JavaScripty

## Define inline partial, pass inline partial, Inline partials have scope

This is matthew's suggestion:

```handlebars
{{# for( val in this.list ) }}
  {{< xyz }}
    {{val}}
  {{/ xyz }}
  <my-custom-element xyz="xyz"></my-custom-element>
{{ / }}
```

This would make inline partials keep their "closure" (aka LetScope) when rendered.  Inline closures would work similar to an arrow function:

```js
let xyz = () => {
  return val;
}
new MyCustomElement().intialize({xyz});
```

Pros:

- More JavaScripty - Inline partials work a lot like arrow functions.

Cons:

- Difficult to implement
- Not a very terse API
- Possibly a breaking change

## Define inline partial + pass inline partial, Inline partials have scope

As a shortcut, I think inline partials defined within an element should be a shorthand:

```handlebars
{{# for( val in this.list ) }}

  <my-custom-element>
  {{< xyz }}
    {{val}}
  {{/ xyz }}
  </my-custom-element>
{{ / }}
```

This would work more like an inline arrow function:

```js
new MyCustomElement().intialize({
  xyz: () => {
    return val;
  }
});
```


Pros:

- More terse usage for the common case of passing child renderers.
- Difficult to implement
- Possibly a breaking change


## Summary 

I think doing 1 then 2 then 3 seems fine.

**Comment by matthewp** [comment]
For #2, I wasn't suggesting that they work like arrow functions, that would be a breaking change. I was suggesting they work like function functions.

**Comment by justinbmeyer** [comment]
I think `function functions` (not capturing `this`) might still be a breaking change as the closure is also not captured presently (I believe).  Does this work:

```handlebars
{{let foo = "bar"}}
{{<myTemplate}} {{foo}} {{/myTemplate}}
{{myTemplate()}}
```

I think that would write out nothing. If `{{foo}}` began to access the let scope (closure) and now wrote out "bar", this might break things.
