### ISSUE TITLE
Example shows using static getter is wrong

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-stache-element#85]
The example that shows how to use static getter in props [page](https://next.canjs.com/doc/can-stache-element/static.props.html) is wrong:

<img width="913" alt="props___can-stache-element___Views___API_Docs___CanJS" src="https://user-images.githubusercontent.com/109013/65983845-626b8c00-e476-11e9-9af3-5474f341b512.png">

**Comment by chasenlehara** [comment]
Also the mention of `define` below that.

**Comment by phillipskevin** [comment]
I'll fix this.
