### ISSUE TITLE
Warn when a component property shadows a DOM Element property

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-stache-element#95]
I ran into an issue with a component defining a [tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) property like this:

```js
class MyComponent extends StacheElement {
  static get view() {
    return "";
  }

  static get props() {
    return {
      tagName: String
    };
  }
}
```

can-stache-bindings throws the following error:

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.viewModel 
    at makeDataBinding
```

There is a warning already in place when components define an `error` property. We should extend that functionality.

**Comment by nlundquist** [comment]
Oddly the example in this issue works fine in Chrome. I'm seeing an issue with Firefox though and agree this should throw a warning at the very least.

**Comment by nlundquist** [comment]
I can't reproduce the error in this issue, but I agree that this should cause a warning.

**Comment by m-mujica** [comment]
I saw this while working on https://github.com/canjs/can-devtools-components/blob/064f639b2c93f169702651b7d56b35ace47953d9/viewmodel-editor/viewmodel-editor.js, maybe if you change [this line](https://github.com/canjs/can-devtools-components/blob/064f639b2c93f169702651b7d56b35ace47953d9/viewmodel-editor/viewmodel-editor.js#L66) to `tagName: String` and try loading the demo page you'll be able to replicate.
